apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "anime-reminder.ui" . }}
  labels:
    {{- include "anime-reminder.labels" . | nindent 4 }}
    component: ui
spec:
  {{- if not .Values.ui.autoscaling.enabled }}
  replicas: {{ .Values.ui.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "anime-reminder.selectorLabels" . | nindent 6 }}
      component: ui
  template:
    metadata:
      {{- with .Values.ui.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "anime-reminder.selectorLabels" . | nindent 8 }}
        component: ui
    spec:
      {{- with .Values.ui.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "anime-reminder.ui.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.ui.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "anime-reminder.ui" . }}
          securityContext:
            {{- toYaml .Values.ui.securityContext | nindent 12 }}
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          {{- if .Values.ui.healthCheck.enabled }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{- end }}
          resources:
            {{- toYaml .Values.ui.resources | nindent 12 }}
          volumeMounts:
          {{- if .Values.ui.devMode.enabled }}
            - mountPath: {{ .Values.ui.devMode.codePathOfPod }}
              name: {{ include "anime-reminder.ui" . }}-dev
          {{- end }}
      {{- with .Values.ui.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      hostAliases:
        - ip: {{ .Values.loadBalancer.ip }}
          hostnames:
          - sc23.group40.io
      volumes:
        {{- if .Values.ui.devMode.enabled }}
        - name: {{ include "anime-reminder.ui" . }}-dev
          hostPath:
            path: {{ .Values.ui.devMode.codePathOfLocal }}
            type: Directory
        {{- end }}