---
- name: Configuration for ansible connection
  hosts: all
  roles:
    - { role: ansible-init }
  tags: ansible-init

- name: Install Helm
  hosts: master
  roles:
    - { role: helm, become: yes }
  tags: k8s


- name: Install k8s
  hosts: all
  roles:
    - { role: pip, become: yes }
    - { role: docker, become: yes }
    - { role: k8s-install, become: yes }
  tags: k8s


- name: Init k8s master
  hosts: master
  roles:
    - { role: k8s-master-init, become: yes }
  tags: k8s

- name: Init k8s worker
  hosts: worker
  roles:
    - { role: k8s-worker-init, become: yes }
  tags: k8s

- name: Install cluster monitor-service
  hosts: master
  roles:
    - { role: deploy-service, service_name: k9s, service_path: ../../monitor-service/k9s, become: yes, tags: monitor-service }
    - { role: deploy-service, service_name: kubernetes-dashboard, service_path: ../../monitor-service/kubernetes-dashboard, tags: monitor-service  }

- name: Install service requirement # Install open-iscsi nfs-common
  hosts: all
  roles:
    - { role: service-requirement, become: yes }
  tags: infra-service

- name: Deploy infra service
  hosts: master
  roles:
    - { role: deploy-service, service_name: calico, service_path: ../../infra-service/calico }
    - { role: deploy-service, service_name: metallb, service_path: ../../infra-service/metallb }
    - { role: deploy-service, service_name: ingress-nginx, service_path: ../../infra-service/ingress-nginx }
    - { role: deploy-service, service_name: longhorn, service_path: ../../infra-service/longhorn }
    - { role: deploy-service, service_name: cert-manager, service_path: ../../infra-service/cert-manager }
  tags: infra-service

- name: Deploy app service
  hosts: master
  roles:
    - { role: deploy-service, service_name: anime-reminder, service_path: ../../app-service/anime-reminder }
  tags: app-service