---
# - name: Configuration for ansible connection
#   hosts: all
#   roles:
#     - { role: ansible-init }
#   tags: ansible-init

# - name: Install Helm
#   hosts: master
#   roles:
#     - { role: helm, become: yes }
#   tags: helm


# - name: Install k8s
#   hosts: all
#   roles:
#     - { role: pip, become: yes }
#     - { role: docker, become: yes }
#     - { role: k8s-install, become: yes }
#   tags: k8s


# - name: Init k8s master
#   hosts: master
#   roles:
#     - { role: k8s-master-init, become: yes }
#   tags: k8s

# - name: Init k8s worker
#   hosts: worker
#   roles:
#     - { role: k8s-worker-init, become: yes }
#   tags: k8s

- name: Deploy infra service
  hosts: master
  roles:
    # - { role: deploy-service, service_name: calico, service_path: ../../infra-service/calico }
    # - { role: deploy-service, service_name: metallb, service_path: ../../infra-service/metallb }
    - { role: deploy-service, service_name: ingress-nginx, service_path: ../../infra-service/ingress-nginx }
  tags: infra-service