apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-root-cert
  namespace: cert-manager
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "2"
spec:
  commonName: "selfsigned-root-cert"
  secretName: selfsigned-root-secret
  isCA: true
  issuerRef:
    name: selfsigned-root-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  duration: 175200h0m0s
  renewBefore: 24h0m0s