---
- name: Check if helm has installed
  command: helm version
  ignore_errors: true
  failed_when: false
  register: helm_has_installed

- name: Extract helm
  unarchive:
    src: helm-v3.11.0-rc.1-linux-arm64.tar
    dest: /tmp
  when: helm_has_installed.rc != 0

- name: move helm binary file
  command: mv /tmp/linux-arm64/helm /usr/local/bin/helm
  when: helm_has_installed.rc != 0

# - name: Add an apt signing key for Kubernetes
#   apt_key:
#     url: https://baltocdn.com/helm/signing.asc
#     validate_certs: no
#     state: present

# - name: Adding apt respository for Helm
#   apt_repository:
#     repo: deb https://baltocdn.com/helm/stable/debian/ all main
#     state: present
#     filename: helm-stable-debian

# - name: Install Helm
#   apt:
#     name: helm
#     update_cache: yes

