{{- if .Values.keycloak.startupScripts }}
{{- $highAvailability := gt (int .Values.replicas) 1 -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "anime-reminder.keycloak" . }}-startup
  labels:
    {{- include "anime-reminder.labels" . | nindent 4 }}
    component: keycloak
data:
  {{- range $key, $value := .Values.keycloak.startupScripts }}
  {{ $key }}: |
    {{- tpl $value $ | nindent 4 }}
  {{- end }}
{{- end -}}
