{{- range $nameSuffix, $values := .Values.keycloak.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "anime-reminder.keycloak" $ }}-{{ $nameSuffix }}
  {{- with $values.annotations }}
  annotations:
  {{- range $key, $value := . }}
  {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
  {{- end }}
  {{- end }}
  labels:
    {{- include "anime-reminder.labels" $ | nindent 4 }}
    component: keycloak
    {{- range $key, $value := $values.labels }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
type: {{ default "Opaque" $values.type }}
{{- with $values.data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- with $values.stringData }}
stringData:
  {{- range $key, $value := . }}
  {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 2 }}
  {{- end }}
{{- end }}
{{- end -}}
