{{- if .Values.keycloak.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "anime-reminder.keycloak.serviceAccountName" . }}
  {{- with .Values.keycloak.serviceAccount.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
  {{- end }}
  labels:
    {{- include "anime-reminder.labels" . | nindent 4 }}
    component: keycloak
    {{- range $key, $value := .Values.keycloak.serviceAccount.labels }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
imagePullSecrets:
  {{- toYaml .Values.keycloak.serviceAccount.imagePullSecrets | nindent 4 }}
{{- end }}
