{{- if .Values.api.canary.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "anime-reminder.api" . }}-canary
  labels:
    {{- include "anime-reminder.labels" . | nindent 4 }}
    component: api
spec:
  {{- if not .Values.api.autoscaling.enabled }}
  replicas: {{ .Values.api.canary.replicaCount }}
  {{- end }}
  strategy:
    type: {{ .Values.api.strategy.type }}
    {{- if (eq "RollingUpdate" .Values.api.strategy.type) }}
    rollingUpdate:
      maxUnavailable: {{ .Values.api.strategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.api.strategy.rollingUpdate.maxSurge }}
    {{- end }}
  selector:
    matchLabels:
      {{- include "anime-reminder.selectorLabels" . | nindent 6 }}
      component: api
  template:
    metadata:
      {{- with .Values.api.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "anime-reminder.selectorLabels" . | nindent 8 }}
        component: api
    spec:
      {{- with .Values.api.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "anime-reminder.api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.api.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "anime-reminder.api" . }}
          securityContext:
            {{- toYaml .Values.api.securityContext | nindent 12 }}
          image: "{{ .Values.api.canary.image.repository }}:{{ .Values.api.canary.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            {{- with .Values.api.extraEnvFrom }}
            {{- tpl . $ | nindent 12 }}
            {{- end }}
          {{- if .Values.api.healthCheck.enabled }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{- end }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          volumeMounts:
          {{- if .Values.api.devMode.enabled }}
            - mountPath: {{ .Values.api.devMode.codePathOfPod }}
              name: {{ include "anime-reminder.api" . }}-dev
          {{- end }}
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      hostAliases:
        - ip: {{ .Values.loadBalancer.ip }}
          hostnames:
          - sc23.group40.io
      volumes:
        {{- if .Values.api.devMode.enabled }}
        - name: {{ include "anime-reminder.api" . }}-dev
          hostPath:
            path: {{ .Values.api.devMode.codePathOfLocal }}
            type: Directory
        {{- end }}
{{- end }}