{{- if .Values.api.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "anime-reminder.api.serviceAccountName" . }}
  labels:
    {{- include "anime-reminder.labels" . | nindent 4 }}
    component: api
  {{- with .Values.api.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
