apiVersion: v1
kind: Secret
metadata:
  name: {{ include "anime-reminder.fullname" . -}}-common
  labels:
    {{- include "anime-reminder.labels" $ | nindent 4 }}
type: Opaque
stringData:
  DB_USER: {{ .Values.postgresql.postgresql.username }}
  DB_PASSWORD: {{ .Values.postgresql.postgresql.password }}
  KEYCLOAK_USER: {{ .Values.keycloak.admin.username }}
  KEYCLOAK_PASSWORD: {{ .Values.keycloak.admin.password }}