apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-reader
subjects:
- kind: ServiceAccount
  name: {{ include "anime-reminder.api.serviceAccountName" . }}
  namespace: anime-reminder
- kind: ServiceAccount
  name: {{ include "anime-reminder.ui.serviceAccountName" . }}
  namespace: anime-reminder