{{- if .Values.extraConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.extraConfigMap.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
data:
  {{- (.Files.Glob "files/*").AsConfig | nindent 2 }}
{{- end }}