---
# Before Deploy, Need to Transfer deploy file to Master Node
- name: Transfer {{ service_path }} to master
  synchronize:
    src: "{{ service_path }}"
    dest: /home/{{ ansible_user }}/k8s/deployment

- name: Change file permissions
  file: 
    path: /home/{{ ansible_user }}/k8s/deployment/{{ service_name }}/{{ item }}
    mode: '0755'
  loop:
    # - check_service.sh
    - deploy.sh
    # - uninstall.sh
  become: yes

- name: Deploy and wait until running
  shell: /home/{{ ansible_user }}/k8s/deployment/{{ service_name }}/deploy.sh
    
# - name: Check {{ role_name }} service
#   shell: /home/{{ ansible_user }}/k8s/deployment/{{ service_name  }}/check_service.sh