# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  ## Master ## 
  config.vm.define "k8s-master" do |node|
    node.vm.box = "starboard/ubuntu-arm64-20.04.5"
    # node.vm.box = "rkrause/ubuntu-20.04-arm64"
    # node.vm.box_version = "1.0.0"
    node.vm.box_version = "20221120.20.40.0"
    node.vm.box_download_insecure = true
    node.vm.hostname = "k8s-master"
    # node.vm.network "private_network", type: "dhcp"
    node.vm.network "private_network", ip: "192.168.2.196"#, auto_config: false

    node.vm.provider "VMware" do |vm|
      vm.name = "k8s-master"        
    end

    node.vm.provider "vmware_desktop" do |v|
      v.ssh_info_public = true
      v.gui = true
      v.linked_clone = false
      v.vmx["ethernet0.virtualdev"] = "vmxnet3"
      v.vmx["ethernet1.pcislotnumber"] = "36"
      v.vmx["ethernet0.pcislotnumber"] = "160"
      # Customize the amount of memory on the VM:
      v.vmx["memsize"] = "4096"
      v.vmx["numvcpus"] = "2"
    end
  end

  ## Worker 1 ## 
  config.vm.define "k8s-worker1" do |node|
    node.vm.box = "starboard/ubuntu-arm64-20.04.5"
    node.vm.box_version = "20221120.20.40.0"
    # node.vm.box = "rkrause/ubuntu-20.04-arm64"
    # node.vm.box_version = "1.0.0"
    node.vm.box_download_insecure = true
    node.vm.hostname = "k8s-worker1"
    # node.vm.network "private_network", type: "dhcp"
    node.vm.network "private_network", ip: "192.168.2.197"

    node.vm.provider "VMware" do |vm|
      vm.name = "k8s-worker1"        
    end

    node.vm.provider "vmware_desktop" do |v|
      v.ssh_info_public = true
      v.gui = true
      v.linked_clone = false
      v.vmx["ethernet0.virtualdev"] = "vmxnet3"
      v.vmx["ethernet1.pcislotnumber"] = "36"
      v.vmx["ethernet0.pcislotnumber"] = "160"
      # Customize the amount of memory on the VM:
      v.vmx["memsize"] = "4096"
      v.vmx["numvcpus"] = "2"
    end
  end

  # ## Client ## 
  # config.vm.define "client" do |node|
  #   node.vm.box = "starboard/ubuntu-arm64-20.04.5"
  #   node.vm.box_version = "20221120.20.40.0"
  #   node.vm.box_download_insecure = true
  #   node.vm.hostname = "client"
  #   # node.vm.network "private_network", type: "dhcp"
  #   # node.vm.network "private_network", ip: "192.168.2.185"

  #   node.vm.provider "VMware" do |vm|
  #     vm.name = "client"        
  #   end

  #   node.vm.provider "vmware_desktop" do |v|
  #     v.ssh_info_public = true
  #     v.gui = true
  #     v.linked_clone = false
  #     v.vmx["ethernet0.virtualdev"] = "vmxnet3"
  #     # v.vmx["ethernet0.pcislotnumber"] = "160"
  #     # Customize the amount of memory on the VM:
  #     v.vmx["memsize"] = "4096"
  #     v.vmx["numvcpus"] = "2"
  #   end
  # end

end
